### PR TITLE
Pact upgrade

### PR DESCRIPTION
**Pull request by magiim**
grep xtail /etc/setup/installed.db| sed 's/\.tar.*//'|awk '{print $2}'

### CODE REVIEW

**Comment by tombujok** [comment]
Big thank you to @magiim for a great cooperation at the yesterday's Hackergarten ;)

**Comment by magiim** [comment]
Thank you too, Tom!

2015-03-11 19:57 GMT+01:00 Tom Bujok <notifications@github.com>:

**Comment by tombujok** [comment]
@maagim Next Hackergarten this Thursday. Will you join us to work a bit more on pact ;)  ? http://www.meetup.com/Trojmiasto-Java-User-Group/events/221949972/

**Comment by magiim** [comment]
Hi Tom!
I think I will! I'm not sure for 100% ;-)


2015-04-21 14:52 GMT+02:00 Tom Bujok <notifications@github.com>:

**Pull request merged**
