### PR TITLE
xserver plugin

### PR DESCRIPTION
**Pull request by jhpaul**
As requested in issue https://github.com/babun/babun/issues/105

This plugin installs and configures xserver. I had some problems that appear to be new since the issue was created, so this solution is somewhat different.

### CODE REVIEW

**Comment by tombujok** [comment]
Wow! How did it happen that I missed this awesome PR... Sorry about that.
It looks awesome. It will definitely needs some testing on our side, but we will definitely come back to you!

**Comment by mtp** [comment]
Hello,
Thanks for this amazing job.
When this PR will be accepted ?

**Comment by wulfgarpro** [comment]
Works

**Comment by tombujok** [comment]
Great plugin! It will be merged after the release that is planned in the next few days.

**Comment by zxytim** [comment]
How's this pull request going? We are looking forward to use X along with babun, and that'll be a great plus to babun.

**Comment by tombujok** [comment]
Thx!

**Comment by jhpaul** [comment]
happy to help (and get functional X forwarding in windows)

**Comment by jlupi** [comment]
Target release 1.3.0 #393

**Pull request merged**
