### PR TITLE
Add cscript failure detection and option to continue

### PR DESCRIPTION
**Pull request by igitur**

### CODE REVIEW

**Comment by igitur** [comment]
There is currently no consistent indentation in that file. Sometimes tabs are used ( https://github.com/babun/babun/blob/master/babun-dist/install/install.bat#L90 ) and sometimes 4 spaces are used ( https://github.com/babun/babun/blob/master/babun-dist/install/install.bat#L121 ).

Which scheme do you want to use?

**Comment by tombujok** [comment]
Good point! Let's use spaces

**Comment by igitur** [comment]
4 spaces or 2 spaces? A `.editorconfig` file here might be useful.

**Comment by tombujok** [comment]
Let's try with 4

**Comment by igitur** [comment]
I'll reindent the entire file in a separate pull request.

**Comment by darinkes** [comment]
Sorry, you are right. just checked the diff content.
:+1: for 4 Spaces

**Comment by tombujok** [comment]
Thx

**Pull request merged**
