### PR TITLE
welcome message: add `babun help`

### PR DESCRIPTION
**Pull request by thomasleveil**
### before

> Welcome to babun - the Windows shell you will love!
> You have got a lot of things under the hood here!
> 
>    pact -> a package manager that handles installation of babun packages
>       pact install tar -> will install tar package on your system
>       pact remove tar -> will remove tar package from your system
> 
>    babun -> a script that manages babun and enables auto-update
>       babun check -> will check the configuration (proxy, connection, etc)
>       babun update -> will update babun to the newest version
>       babun --welcome -> will display this message again
> 
> There is a couple of plugins installed by default: oh-my-zsh, pact, cacert, etc.
> There is also a lot of dev tools such as git, svn, unix utils, etc
> If you would like to contribute, code up a plugin or report an issue just
> go to github: https://github.com/babun/babun
> 
> If you like the project star it on github and follow me on twitter!
> This project is created and maintained by Tom Bujok (@tombujok)

### after

> Welcome to babun - the Windows shell you will love!
> You have got a lot of things under the hood here!
> 
>    pact -> a package manager that handles installation of babun packages
>       pact install tar -> will install tar package on your system
>       pact remove tar -> will remove tar package from your system
> 
>    babun -> a script that manages babun and enables auto-update
>       **babun help -> will display babun script usage**
>       babun check -> will check the configuration (proxy, connection, etc)
>       babun update -> will update babun to the newest version
>       babun --welcome -> will display this message again
> 
> There is a couple of plugins installed by default: oh-my-zsh, pact, cacert, etc.
> There is also a lot of dev tools such as git, svn, unix utils, etc
> If you would like to contribute, code up a plugin or report an issue just
> go to github: https://github.com/babun/babun
> 
> If you like the project star it on github and follow me on twitter!
> This project is created and maintained by Tom Bujok (@tombujok)

### CODE REVIEW

**Comment by tombujok** [comment]
Thx! This one is tricky as the length was adjusted to the initial size of the babun window, so that all lines are visible ;)
I would probably get rid of this one `babun shell /bin/bash -> will make bash the default shell`

**Comment by thomasleveil** [comment]
PR updated to add only `babun help`

**Comment by jlupi** [comment]
cheers

**Comment by jlupi** [comment]
#393

**Pull request merged**
