### PR TITLE
Babun Shell here

### PR DESCRIPTION
**Pull request by kubamarchwicki**
This is an extended implementation of #141, fixing #183 - base on a `chere` command.
Removing additional call to `source /etc/zprofile` (from #205) allows opening Babun in a desired folder - though I'm not sure on the implications here

The rest is a plugin which adds appropriate context menu item to open Babun where needed. 

I'd appreciate feedback

### CODE REVIEW

**Comment by tombujok** [comment]
Hej Kuba! Thanks for your contribution - it looks awesome!
I've added some inlined comments

**Comment by kubamarchwicki** [comment]
And for the future reference - I definitely need to squash before commit; I just made reviewing the code pretty painful ;-)

**Comment by kubamarchwicki** [comment]
@tombujok I think most sensible will be to close this one and I'll setup a single pull request with the changes squashed?

**Comment by tombujok** [comment]
@kubamarchwicki yep, exactly.

**Pull request closed without merging**
