### PR TITLE
Upgrading cygwin

### PR DESCRIPTION
**Pull request by airborn**
Added script for upgrading cygwin

### CODE REVIEW

**Comment by tombujok** [comment]
Yes, I agree. Probably we need all 3 of them
-n --no-shortcuts               
 -N --no-startmenu                 
 -d --no-desktop

**Comment by shunia** [comment]
As there is this issue related to updating Cygwin,I'm not gonna open another one to interrupt.
With Babun version 1.1.1,I got stuck in the middle of updating Cygwin modules with poor internet access,I have to cancel the updating process.But when I then returned to the interface of Babun,it just shows everything is up to date(Babun and Cygwin).And after this,the command 'babun update' just shows up-to-date all the time.
So,how can I trigger a Cygwin update manually by now?

**Comment by tombujok** [comment]
Run update.bat manually. It's located in the main .babun folder.

**Comment by shunia** [comment]
@tombujok It really works,thx!

**Pull request merged**
