### PR TITLE
Making the ahk script more robust

### PR DESCRIPTION
**Pull request by v-yadli**

### CODE REVIEW

**Comment by tombujok** [comment]
Did you want to change the akh.exe only?

**Comment by v-yadli** [comment]
yes. I've compiled the script to that executable(it's not the ahk engine).

**Comment by tombujok** [comment]
I see, could you also commit the source file, and maybe a bat that compiles it? So that we may be able to recompile it afterwards...?

**Comment by v-yadli** [comment]
The source is in the comment of #239. Compiling the script requires ahk to be installed(http://www.autohotkey.com/). Just wondering where should I place the source script, as it should not be a part of the distribution.

**Comment by tombujok** [comment]
OK, I see. Maybe just put it to tools too, I will filter it out in the
build.

**Comment by v-yadli** [comment]
There you go #256 :-)

**Comment by FichteFoll** [comment]
May I suggest to rename the exe? `tools/ahk.exe` heavily suggest it would be the default ahk engine and not a compiled script.

Also, afaik the compile process includes the actual engine in compiled binaries anyway and then just runs the bundled source (at least that's what happens with AutoIt). This seems to be the case for ahk too since the compiler code is really simple and it's **probably a better idea to ship the actual engine executable and invoke the `.ahk` install script via CLI**. That would also allow to modify the script without updating the binary.

From the documentation there appear to be 3 versions of the executable, ANSI and Unicode x86/x64: http://ahkscript.org/docs/Scripts.htm#install. These are also all included in the installation folder.

This also seems to be relevant for the compiled exe since it uses a different `.bin` file depending on settings or the installed version if none was specified, so the same limitations apply. ([ahk2exe source](https://github.com/fincs/Ahk2Exe/blob/212f0170ff20deaa9cca984a30e89f5873421937/Ahk2Exe.ahk#L161-L177)) Idk about the ANSI variant, but otherwise U32 should be the version with most compatability.

**Comment by v-yadli** [comment]
@FichteFoll Totally agreed. My bad for such a confusing name! :-D Didn't know ahk2exe is made in ahk and I thought it would do some AOT compilation.

I'll clean it a bit and submit a pull request tonight.

**Comment by FichteFoll** [comment]
Anyway, seems like this is not needed anymore :smile:

**Pull request merged**
